dirigiu(chicago,marshall).
dirigiu(amnesia,nolan).
dirigiu(babel,inarritu).
dirigiu(senhorDosAneis,jackson).
dirigiu(capote,miller).
dirigiu(casablanca,curtiz).
dirigiu(belezaAmericana,mendes).
dirigiu(matrix,wachowsk).
dirigiu(meninaDeOuro,clint).
dirigiu(shrek,adamson).
dirigiu(titanic,cameron).
dirigiu(gladiador,scott).
dirigiu(umaMenteBrilhante,howard).
diretorMelhorFilme(2003,marshall).
diretorMelhorFilme(2004,jackson).
diretorMelhorFilme(2000,mendes).
diretorMelhorFilme(2005,clint).
diretorMelhorFilme(2001,scott).
diretorMelhorFilme(2002,howard).
genero(titanic,drama).
genero(shrek,animacao).
melhorFilme(mendes).
melhorFilme(scott).
melhorFilme(howard).
melhorFilme(marshall).
melhorFilme(jackson).
melhorFilme(clint).
